# Generated by Django 3.0.3 on 2020-03-02 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics', verbose_name='Upload a profile picture (optional)')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', "Don't specify")], default='Unknown', max_length=30)),
                ('address1', models.CharField(max_length=1024, null=True, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, null=True, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=1024, null=True)),
                ('postcode', models.CharField(max_length=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
