# Generated by Django 3.0.3 on 2020-03-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_token',
            field=models.IntegerField(default=0),
        ),
    ]
