# Generated by Django 3.0.3 on 2020-02-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
