# Generated by Django 3.0.3 on 2020-03-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_blog', '0002_remove_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blog_img/default.jpg', upload_to='blog_img'),
        ),
    ]
