# Generated by Django 3.0.3 on 2020-03-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_blog', '0002_auto_20200313_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='headline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='instructions',
            field=models.TextField(null=True),
        ),
    ]
