# Generated by Django 3.0.3 on 2020-03-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_blog', '0004_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='star_question',
            field=models.BooleanField(default=False),
        ),
    ]
