# Generated by Django 3.0.3 on 2020-03-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='session_token',
            field=models.IntegerField(default=0),
        ),
    ]
